netty:
  port: 8080
  threads:
    worker: 1
    acceptor: 1
  backlog: 100

# logging level
logging:
  level:
    org:
      springframework: info
    io:
      netty: info
    com:
      example: info